//! Generating the I2P router's configuration.
//!
//! This is the I2P counterpart of [`crate::torrc`], and the same rule applies: what is deliberately
//! **absent** matters as much as what is present. In particular this renderer will never emit:
//!
//! * a proxy bound to anything but loopback — the machine-wide policy guards those ports on input,
//!   but the listeners themselves are for this machine only;
//! * the router console, SAM, or UPnP: extra listeners and an extra control surface with no job in
//!   this design;
//! * any tunnelling of I2P over Tor: the two networks are alternatives, never layers (M9 decision 5).
//!
//! The router's *transports* (NTCP2/SSU2) are deliberately not configured here: they must accept
//! connections from I2P peers, and their addresses/ports are the router's own business. The policy
//! exempts the router's uid, which is what makes them reachable.

use std::path::PathBuf;

use ghostnector_spec::backend::I2pPorts;

/// The settings Ghostnector puts into the router's configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct I2pSettings {
    /// Port the router's HTTP proxy listens on. Loopback only.
    pub http_proxy_port: u16,
    /// Port the router's SOCKS proxy listens on. Loopback only.
    pub socks_proxy_port: u16,
    /// The router's data directory.
    pub data_directory: PathBuf,
}

impl Default for I2pSettings {
    fn default() -> Self {
        Self {
            http_proxy_port: I2pPorts::default().http,
            socks_proxy_port: I2pPorts::default().socks,
            data_directory: PathBuf::from("/var/lib/ghostnector-i2pd"),
        }
    }
}

impl I2pSettings {
    /// Adopt the proxy ports the policy actually guards.
    pub fn with_ports(mut self, ports: I2pPorts) -> Self {
        self.http_proxy_port = ports.http;
        self.socks_proxy_port = ports.socks;
        self
    }
}

/// Render the router's configuration file.
pub fn render(settings: &I2pSettings) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by Ghostnector. Do not edit: it is rewritten whenever protection starts.\n\
         #\n\
         # This router is a client of the I2P network. Its transports reach peers directly, because\n\
         # that is what the network is; everything else on this machine reaches I2P only through the\n\
         # loopback proxies below.\n",
    );
    // systemd tracks the process, so the router must not detach from it.
    out.push_str("daemon = false\n");
    out.push_str("log = stdout\n");
    out.push_str("loglevel = warn\n");
    out.push_str(&format!(
        "datadir = {}\n\n",
        settings.data_directory.display()
    ));

    out.push_str(
        "# The two proxies applications use. Loopback only: the policy drops these ports from any\n\
         # other interface, and this is the first line of that defence.\n",
    );
    out.push_str("[httpproxy]\n");
    out.push_str("enabled = true\n");
    out.push_str("address = 127.0.0.1\n");
    out.push_str(&format!("port = {}\n\n", settings.http_proxy_port));
    out.push_str("[socksproxy]\n");
    out.push_str("enabled = true\n");
    out.push_str("address = 127.0.0.1\n");
    out.push_str(&format!("port = {}\n\n", settings.socks_proxy_port));

    out.push_str(
        "# Listeners this design has no job for. The console is an administrative surface, SAM is a\n\
         # second proxy protocol, and UPnP would ask the local network to open ports.\n",
    );
    out.push_str("[http]\nenabled = false\n\n");
    out.push_str("[sam]\nenabled = false\n\n");
    out.push_str("[upnp]\nenabled = false\n\n");

    out.push_str(
        "# Reseed material is verified, so a hostile mirror cannot hand this router a poisoned\n\
         # view of the network.\n",
    );
    out.push_str("[reseed]\nverify = true\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings() -> I2pSettings {
        I2pSettings::default()
    }

    fn rendered() -> String {
        render(&settings())
    }

    #[test]
    fn both_proxies_are_loopback_only() {
        let text = rendered();
        assert!(text.contains("[httpproxy]"), "{text}");
        assert!(text.contains("[socksproxy]"), "{text}");
        assert!(text.contains("address = 127.0.0.1"), "{text}");
        assert!(
            !text.contains("0.0.0.0"),
            "the renderer must never bind a proxy to a wildcard:\n{text}"
        );
        for line in text.lines().filter(|line| line.starts_with("address")) {
            assert_eq!(line, "address = 127.0.0.1", "unexpected bind: {line}");
        }
    }

    #[test]
    fn the_listeners_and_control_surfaces_this_design_has_no_job_for_are_off() {
        let text = rendered();
        for section in ["[http]", "[sam]", "[upnp]"] {
            let start = text
                .find(section)
                .unwrap_or_else(|| panic!("missing {section}"));
            let rest = &text[start..];
            let end = rest[1..]
                .find('[')
                .map(|offset| start + 1 + offset)
                .unwrap_or(text.len());
            let block = &text[start..end];
            assert!(
                block.contains("enabled = false"),
                "{section} must be disabled, found:\n{block}"
            );
        }
    }

    #[test]
    fn the_router_does_not_detach_from_its_service_manager() {
        assert!(rendered().contains("daemon = false"));
    }

    #[test]
    fn reseed_material_is_verified() {
        let text = rendered();
        assert!(text.contains("[reseed]"), "{text}");
        assert!(text.contains("verify = true"), "{text}");
    }

    #[test]
    fn ports_and_paths_come_from_the_settings_not_from_constants() {
        let text = render(&I2pSettings {
            http_proxy_port: 14444,
            socks_proxy_port: 14447,
            data_directory: PathBuf::from("/tmp/i2pd-data"),
        });
        for expected in ["port = 14444", "port = 14447", "datadir = /tmp/i2pd-data"] {
            assert!(text.contains(expected), "missing '{expected}' in:\n{text}");
        }
    }

    #[test]
    fn the_policy_ports_are_adopted() {
        let settings = I2pSettings::default().with_ports(I2pPorts {
            http: 14444,
            socks: 14447,
        });
        assert_eq!(settings.http_proxy_port, 14444);
        assert_eq!(settings.socks_proxy_port, 14447);
    }

    #[test]
    fn no_tunnelling_of_i2p_over_tor_can_be_configured() {
        let text = rendered();
        // The renderer has no outproxy setting at all: the two networks are alternatives, never
        // layers, so there is no configuration surface that could chain one through the other.
        for refused in ["socksproxy.outproxy", "httpproxy.outproxy", "outproxy"] {
            assert!(
                !text.to_lowercase().contains(&refused.to_lowercase()),
                "{refused} must not appear: the networks are alternatives, never layers"
            );
        }
    }

    #[test]
    fn the_rendered_config_can_be_exported_for_the_qualification_run() {
        // Qualification-only. When the environment names a path, this writes the product's *own*
        // rendered configuration there, so the real-i2pd run uses exactly what the product would
        // write rather than a hand-made copy. Nothing is written otherwise.
        let Ok(path) = std::env::var("GHOSTNECTOR_EXPORT_I2PD_CONF") else {
            return;
        };
        let data_directory = std::env::var("GHOSTNECTOR_EXPORT_I2PD_DATA")
            .unwrap_or_else(|_| "/var/lib/ghostnector-i2pd".to_string());
        let settings = I2pSettings {
            data_directory: PathBuf::from(data_directory),
            ..I2pSettings::default()
        };
        std::fs::write(&path, render(&settings)).expect("export the rendered config");
    }
}
