//! Generating Tor's configuration.
//!
//! Every setting here is present for a reason, and the settings that are deliberately **absent**
//! matter just as much. In particular this renderer will never emit:
//!
//! * `ConnectionPadding 0` — padding costs bandwidth and buys resistance to traffic analysis. The
//!   review refuses that trade (see "Optimizations that must be refused").
//! * `ExitNodes` / `StrictNodes` — pinning exits shrinks the anonymity set and gives the user a
//!   fingerprint. Usability is not worth it.
//! * `MaxCircuitDirtiness` tweaks — per-application isolation is achieved with namespaces and
//!   credentials (M8), not by churning circuits.
//! * `DisableNetwork` games or a relay/exit/hidden-service configuration: this Tor is a client.
//!
//! A test below asserts those absences, so a future "optimisation" has to argue with the test suite.

use std::path::PathBuf;

use ghostnector_spec::backend::Ports;

/// The settings Ghostnector puts into Tor's configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TorSettings {
    /// Port for transparent TCP proxying. Must be loopback: the firewall's `redirect` sends local
    /// traffic to `127.0.0.1`.
    pub trans_port: u16,
    /// Port for DNS resolution inside Tor.
    pub dns_port: u16,
    /// Port for applications that speak SOCKS directly.
    pub socks_port: u16,
    /// Port for Ghostnector's health checks. Loopback, cookie-authenticated.
    pub control_port: u16,
    /// Tor's data directory.
    pub data_directory: PathBuf,
    /// Where Tor writes the control-port cookie. Must be readable by the control plane's group.
    pub cookie_path: PathBuf,
    /// Whether to enable Tor's own seccomp sandbox.
    pub sandbox: bool,
    /// The host-local APP core address. When set, the transparent proxy and SOCKS listeners move
    /// there so an APP namespace's DNAT has somewhere to deliver; the DNS and control listeners
    /// stay on loopback. `None` keeps every listener on loopback (the machine-wide profiles).
    pub app_core: Option<std::net::Ipv4Addr>,
}

impl Default for TorSettings {
    fn default() -> Self {
        Self {
            trans_port: 9040,
            // Tor's DNS listener, which is where the DNS chokepoint forwards. It is deliberately
            // not the chokepoint's own port: see `with_ports`.
            dns_port: 9053,
            socks_port: 9050,
            control_port: 9051,
            data_directory: PathBuf::from("/var/lib/tor"),
            // Tor writes this cookie itself, so it lives in a directory owned by Tor's service
            // account with the control plane's group (setgid) so the unprivileged control plane
            // can read it. The packaged tmpfiles entry creates it; see packaging/.
            cookie_path: PathBuf::from("/run/ghostnector-tor/control.cookie"),
            sandbox: true,
            app_core: None,
        }
    }
}

impl TorSettings {
    /// Adopt the ports the firewall actually redirects into.
    ///
    /// Note what is *not* adopted: Tor's `DNSPort` is where the DNS chokepoint forwards to, which is
    /// a different port from the chokepoint's own listener. Conflating the two would point Tor's
    /// resolver at the process that was supposed to be pointing at Tor.
    pub fn with_ports(mut self, ports: Ports) -> Self {
        self.trans_port = ports.trans;
        self.socks_port = ports.socks;
        self
    }

    /// Move the transparent proxy and SOCKS listeners to the APP core address.
    ///
    /// This is what makes an APP session usable: the namespace's DNAT delivers to `core:trans`, and
    /// the core address exists only on the host's private bridge. The DNS and control listeners stay
    /// on loopback; there is no wildcard bind in either mode.
    pub fn with_app_core(mut self, core: std::net::Ipv4Addr) -> Self {
        self.app_core = Some(core);
        self
    }
}

/// Render Tor's configuration file.
pub fn render(settings: &TorSettings) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by Ghostnector. Do not edit: it is rewritten whenever protection starts.\n\
         #\n\
         # This Tor is a client and nothing else. It does not relay, it does not exit, and it hosts\n\
         # no hidden services.\n",
    );
    out.push_str("ClientOnly 1\n\n");

    out.push_str(
        "# Transparent proxying. The listeners are loopback-only in the machine-wide profiles,\n\
         # because the firewall's redirect targets 127.0.0.1 and the input chain drops anything\n\
         # arriving for these ports from off-host. In APP scope they move to the private core\n\
         # address that app namespaces DNAT to; never a wildcard. SOCKS keeps a per-credential\n\
         # circuit, which is how a browser profile gets its own circuits without this file knowing\n\
         # about it.\n",
    );
    let proxy_address = match settings.app_core {
        Some(core) => core.to_string(),
        None => "127.0.0.1".to_string(),
    };
    out.push_str(&format!(
        "SocksPort {proxy_address}:{} IsolateSOCKSAuth KeepAliveIsolateSOCKSAuth\n",
        settings.socks_port
    ));
    out.push_str(&format!(
        "TransPort {proxy_address}:{}\n",
        settings.trans_port
    ));
    out.push_str(&format!("DNSPort 127.0.0.1:{}\n\n", settings.dns_port));

    out.push_str(
        "# Names inside the network resolve to addresses in a reserved range, so a .onion address\n\
         # works through the transparent proxy rather than leaking to a resolver.\n\
         AutomapHostsOnResolve 1\n\
         VirtualAddrNetworkIPv4 10.192.0.0/10\n\n",
    );

    out.push_str(
        "# Health only, and only from this machine. The cookie is how the control plane proves it\n\
         # is allowed to ask; nothing else needs to talk to this port.\n",
    );
    out.push_str(&format!(
        "ControlPort 127.0.0.1:{}\n",
        settings.control_port
    ));
    out.push_str("CookieAuthentication 1\n");
    out.push_str(&format!(
        "CookieAuthFile {}\n",
        settings.cookie_path.display()
    ));
    out.push_str("CookieAuthFileGroupReadable 1\n\n");

    out.push_str(
        "# Local state, and a log that goes to the service manager rather than to disk.\n",
    );
    out.push_str(&format!(
        "DataDirectory {}\n",
        settings.data_directory.display()
    ));
    out.push_str("Log notice stdout\n");
    out.push_str("SafeLogging 1\n");
    out.push_str("AvoidDiskWrites 1\n\n");

    if settings.sandbox {
        out.push_str(
            "# Tor's own seccomp sandbox: a compromise inside Tor is still a compromise, and this\n\
             # is the cheapest way to make it a smaller one.\n\
             Sandbox 1\n",
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings() -> TorSettings {
        TorSettings {
            data_directory: PathBuf::from("/var/lib/tor"),
            cookie_path: PathBuf::from("/run/ghostnector-tor/control.cookie"),
            ..TorSettings::default()
        }
    }

    fn rendered() -> String {
        render(&settings())
    }

    #[test]
    fn every_listener_is_loopback_only_unless_app_scope_moves_the_proxies() {
        let text = rendered();
        assert!(text.contains("SocksPort 127.0.0.1:9050"), "{text}");
        assert!(text.contains("TransPort 127.0.0.1:9040"), "{text}");
        assert!(text.contains("DNSPort 127.0.0.1:9053"), "{text}");
        assert!(text.contains("ControlPort 127.0.0.1:9051"), "{text}");
        assert!(!text.contains("0.0.0.0"), "{text}");

        // APP scope: the proxies move to the private core address; DNS and control stay loopback.
        let app = render(&settings().with_app_core(std::net::Ipv4Addr::new(10, 200, 0, 1)));
        assert!(app.contains("SocksPort 10.200.0.1:9050"), "{app}");
        assert!(app.contains("TransPort 10.200.0.1:9040"), "{app}");
        assert!(app.contains("DNSPort 127.0.0.1:9053"), "{app}");
        assert!(app.contains("ControlPort 127.0.0.1:9051"), "{app}");
        assert!(!app.contains("0.0.0.0"), "{app}");
        for line in app.lines().filter(|line| line.contains("Port ")) {
            assert!(
                line.contains("127.0.0.1") || line.contains("10.200.0.1"),
                "a listener is neither loopback nor the core address: {line}"
            );
        }
    }

    #[test]
    fn this_tor_is_a_client_and_nothing_else() {
        let text = rendered();
        assert!(text.contains("ClientOnly 1"), "{text}");
        for forbidden in [
            "ExitRelay",
            "ORPort",
            "DirPort",
            "HiddenServiceDir",
            "Bridge",
        ] {
            assert!(
                !text.contains(forbidden),
                "a client-only Tor must not configure {forbidden}"
            );
        }
    }

    #[test]
    fn the_control_port_requires_the_cookie() {
        let text = rendered();
        assert!(text.contains("CookieAuthentication 1"), "{text}");
        assert!(
            text.contains("CookieAuthFileGroupReadable 1"),
            "the control plane runs as its own user and must be able to read the cookie"
        );
    }

    #[test]
    fn the_settings_that_would_trade_privacy_for_speed_are_never_emitted() {
        let text = rendered();
        for refused in [
            "ConnectionPadding 0",
            "ExitNodes",
            "StrictNodes",
            "MaxCircuitDirtiness",
            "DisableNetwork",
            "UseBridges",
        ] {
            assert!(
                !text.contains(refused),
                "{refused} must not appear: it changes the privacy properties"
            );
        }
    }

    #[test]
    fn logs_never_carry_addresses_and_stay_off_disk() {
        let text = rendered();
        assert!(text.contains("SafeLogging 1"), "{text}");
        assert!(text.contains("AvoidDiskWrites 1"), "{text}");
        assert!(text.contains("Log notice stdout"), "{text}");
    }

    #[test]
    fn the_sandbox_can_be_turned_off_and_is_on_by_default() {
        assert!(rendered().contains("Sandbox 1"));
        assert!(!render(&TorSettings {
            sandbox: false,
            ..settings()
        })
        .contains("Sandbox 1"));
    }

    #[test]
    fn onion_names_are_mapped_rather_than_resolved() {
        let text = rendered();
        assert!(text.contains("AutomapHostsOnResolve 1"), "{text}");
        assert!(
            text.contains("VirtualAddrNetworkIPv4 10.192.0.0/10"),
            "{text}"
        );
    }

    #[test]
    fn ports_and_paths_come_from_the_settings_not_from_constants() {
        let text = render(&TorSettings {
            trans_port: 19040,
            dns_port: 19054,
            socks_port: 19050,
            control_port: 19051,
            data_directory: PathBuf::from("/tmp/tor-data"),
            cookie_path: PathBuf::from("/tmp/tor-cookie"),
            sandbox: false,
            app_core: None,
        });
        for expected in [
            "TransPort 127.0.0.1:19040",
            "DNSPort 127.0.0.1:19054",
            "SocksPort 127.0.0.1:19050",
            "ControlPort 127.0.0.1:19051",
            "DataDirectory /tmp/tor-data",
            "CookieAuthFile /tmp/tor-cookie",
        ] {
            assert!(text.contains(expected), "missing '{expected}' in:\n{text}");
        }
    }

    #[test]
    fn socks_isolates_by_credential_so_a_browser_profile_gets_its_own_circuits() {
        let text = rendered();
        assert!(text.contains("IsolateSOCKSAuth"), "{text}");
        assert!(text.contains("KeepAliveIsolateSOCKSAuth"), "{text}");
    }

    #[test]
    fn the_firewall_ports_are_adopted_and_tors_dns_port_is_not() {
        let settings = TorSettings::default().with_ports(Ports {
            trans: 19040,
            chokepoint: 19054,
            socks: 19050,
        });
        assert_eq!(settings.trans_port, 19040);
        assert_eq!(settings.socks_port, 19050);
        assert_eq!(
            settings.dns_port,
            TorSettings::default().dns_port,
            "Tor's DNS port is where the chokepoint forwards, not the chokepoint's own port"
        );
        assert_ne!(
            settings.dns_port, 19054,
            "reusing the chokepoint's port would point Tor at the process that points at Tor"
        );
    }
}
